[server]
# can be a port (int)...
# or a unix socket path (e.g. /tmp/sock)
port = 2000

[server.frontend]
# the amount of search results to show
# max 25, min 5
search_count = 5
# displayed codecs, recommended to use default
# see src/downloader/index.ts for a list of codecs
displayed_codecs = ["aac_legacy", "aac_he_legacy"]

[downloader]
# path to the ffmpeg binary
# will get from PATH if simply "ffmpeg"
ffmpeg_path = "ffmpeg"
# path to the yt-dlp binary
# will get from PATH if simply "yt-dlp"
ytdlp_path = "yt-dlp"

[downloader.cache]
# where to store downloaded files (music, lyrics, etc.)
# this directory will be created if it does not exist
directory = "cache"
# how long to keep downloaded files (in seconds)
ttl = 3600 # (1 hour)

[downloader.api]
# two letter language code (ISO 639-1), followed by a dash (-) and a two letter country code (ISO 3166-1 alpha-2)
# recommended to use something similar to your `ITUA` env variable
language = "en-US"
